jetAK8puppi_pt
jetAK8puppi_pt_2
jetAK8puppi_pt_3






FatJet_deepTagMD_H4qvsQCD
FatJet_deepTagMD_HbbvsQCD
FatJet_deepTagMD_TvsQCD
FatJet_deepTagMD_WvsQCD
FatJet_deepTagMD_ZHbbvsQCD
FatJet_deepTagMD_ZHccvsQCD
FatJet_deepTagMD_ZbbvsQCD
FatJet_deepTagMD_ZvsQCD
FatJet_deepTagMD_bbvsLight
FatJet_deepTagMD_ccvsLight
FatJet_deepTagMD_probHbb
FatJet_deepTagMD_probHcc
FatJet_deepTagMD_probHqqqq
FatJet_deepTagMD_probQCDb
FatJet_deepTagMD_probQCDbb
FatJet_deepTagMD_probQCDc
FatJet_deepTagMD_probQCDcc
FatJet_deepTagMD_probQCDothers
FatJet_deepTagMD_probTbc
FatJet_deepTagMD_probTbcq
FatJet_deepTagMD_probTbq
FatJet_deepTagMD_probTbqq
FatJet_deepTagMD_probWcq
FatJet_deepTagMD_probWqq
FatJet_deepTagMD_probZbb
FatJet_deepTagMD_probZcc
FatJet_deepTagMD_probZqq
FatJet_deepTag_H
FatJet_deepTag_QCD
FatJet_deepTag_QCDothers
FatJet_deepTag_TvsQCD
FatJet_deepTag_WvsQCD
FatJet_deepTag_ZvsQCD
FatJet_deepTag_probHbb
FatJet_deepTag_probHcc
FatJet_deepTag_probHqqqq
FatJet_deepTag_probQCDb
FatJet_deepTag_probQCDbb
FatJet_deepTag_probQCDc
FatJet_deepTag_probQCDcc
FatJet_deepTag_probQCDothers
FatJet_deepTag_probTbc
FatJet_deepTag_probTbcq
FatJet_deepTag_probTbq
FatJet_deepTag_probTbqq
FatJet_deepTag_probWcq
FatJet_deepTag_probWqq
FatJet_deepTag_probZbb
FatJet_deepTag_probZcc
FatJet_deepTag_probZqq




float $1;
fChain->SetBranchAddress("$1",&$1,&b_$1);
TBranch        *b_$1;
